version: '3'

services:
  portainer:
    image: portainer/portainer
    command: >
      -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - feeliks
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  speech_to_text_master:
    image: raitraidma/feeliks_speech_to_text_master:0.1
    ports:
      - 8888:8888
    networks:
      - feeliks
    deploy:
      replicas: 1
      restart_policy:
        condition: none

  speech_to_text_worker:
    image: raitraidma/feeliks_speech_to_text_worker_et:0.1
    networks:
      - feeliks
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    depends_on:
      - speech_to_text_master

  text_to_speech:
    image: raitraidma/feeliks_text_to_speech_et_female:0.1
    networks:
      - feeliks
    deploy:
      replicas: 1
      restart_policy:
        condition: none

networks:
  feeliks: