version: '3'

services:
  portainer:
    image: portainer/portainer
    command: >
      -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - feeliks
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  speech_to_text_master:
    image: raitraidma/feeliks.stt.kaldi.master:0.1
    networks:
      - feeliks
    deploy:
      replicas: 1
      restart_policy:
        condition: none

  speech_to_text_worker:
    image: raitraidma/feeliks.stt.kaldi.worker.et.female:0.1
    networks:
      - feeliks
    environment:
      - KALDI_MASTER_HOST=speech_to_text_master
      - KALDI_MASTER_PORT=9000
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    depends_on:
      - speech_to_text_master

  speech_to_text:
    image: raitraidma/feeliks.stt:0.1
    ports:
      - 8888:9000
    networks:
      - feeliks
    environment:
      - SERVER_PORT=9000
      - APP_ENGINE=kaldi
      - APP_KALDI_HOST=speech_to_text_master
      - APP_KALDI_PORT=9000
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    depends_on:
      - speech_to_text_master

networks:
  feeliks: