---

- hosts: all-swarm-nodes
  roles:
    - swarm-common

- hosts: swarm-primary-manager
  roles:
    - swarm-primary-manager
    - java
    - maven

- hosts: swarm-workers
  roles:
    - swarm-worker
